services:
  worker:
    build: ./worker
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    environment:
      - REDIS_URL=redis://100.68.227.68:6379
      - OLLAMA_URL=${REMOTE_OLLAMA_URL}
      - OLLAMA_MODEL=smollm:135m
      - HEARTBEAT_INTERVAL_SECONDS=2
      - HEARTBEAT_TTL_SECONDS=8
      - RESULT_TTL_SECONDS=300
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Mount host system stats and logs folder
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./logs:/app/logs