services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "0.0.0.0:6379:6379"

  master:
    build: ./master
    ports:
      - "0.0.0.0:8001:8001"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
      - SCHEDULER_STRATEGY=least_connections
      - HEARTBEAT_TIMEOUT_SECONDS=8
      - PROCESSING_STALE_SECONDS=45
      - MAX_ATTEMPTS=3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    build: ./gateway
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
      - REQUEST_TIMEOUT_SECONDS=120
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - master

  # worker:
  #   build: ./worker
  #   environment:
  #     - OLLAMA_URL=http://host.docker.internal:11434
  #     - OLLAMA_MODEL=smollm2
  #     - HEARTBEAT_INTERVAL_SECONDS=2
  #     - HEARTBEAT_TTL_SECONDS=8
  #     - RESULT_TTL_SECONDS=300
  #   depends_on:
  #     - redis
  #     - master
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  worker_remote:
    build: ./worker
    environment:
      - REDIS_URL=${REDIS_URL}
      - OLLAMA_URL=${REMOTE_OLLAMA_URL}
      - OLLAMA_MODEL=smollm:135M
      - HEARTBEAT_INTERVAL_SECONDS=2
      - HEARTBEAT_TTL_SECONDS=8
      - RESULT_TTL_SECONDS=300
    extra_hosts:
      - "host.docker.internal:host-gateway"